name: dreamt
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - backports=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cffi=1.17.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.10.17
  - cycler=0.12.1
  - cython=3.0.12
  - dcor=0.6
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - fdasrsf=2.6.1
  - findiff=0.12.1
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.3
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lightgbm=4.1.0
  - llvm-openmp=20.1.3
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multimethod=2.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openjpeg=2.5.3
  - openssl=3.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytz=2025.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - rdata=0.11.2
  - readline=8.2
  - scikit-datasets=0.2.4
  - scikit-fda=0.10.1
  - scipy=1.15.2
  - setuptools=79.0.1
  - six=1.17.0
  - stack_data=0.6.3
  - sympy=1.13.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xarray=2025.3.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aeon==0.5.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==3.0.0
      - confection==0.1.3
      - cymem==2.0.8
      - deprecated==1.2.14
      - docker-pycreds==0.4.0
      - fastai==2.7.13
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastjsonschema==2.19.0
      - fastprogress==1.0.3
      - filelock==3.18.0
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - fsspec==2024.12.0
      - future==0.18.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gpboost==1.2.7.1
      - heartpy==1.2.7
      - hmmlearn==0.3.0
      - hyperopt==0.2.7
      - idna==3.4
      - imbalanced-learn==0.11.0
      - ipywidgets==8.1.1
      - jinja2==3.1.6
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyterlab-widgets==3.0.9
      - langcodes==3.3.0
      - lightning==2.1.0
      - lightning-utilities==0.9.0
      - llvmlite==0.41.1
      - markupsafe==2.1.2
      - matplotlib==3.8.1
      - seaborn==0.13.0
      - mne==1.5.1
      - multidict==6.0.4
      - murmurhash==1.0.10
      - nbformat==5.9.2
      - networkx==3.4.2
      - neurokit2==0.2.7
      - shap==0.47.2